CREATE TABLE [dbo].[Computer]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [CPU] NVARCHAR(MAX) NOT NULL, 
    [GPU] NVARCHAR(MAX) NULL, 
    [PSU] NVARCHAR(MAX) NOT NULL, 
    [MOBO] NVARCHAR(MAX) NOT NULL, 
    [RAM ] NVARCHAR(MAX) NOT NULL, 
    [HDD] NVARCHAR(MAX) NOT NULL, 
    [SSD] NVARCHAR(MAX) NULL, 
    [CASE] NVARCHAR(MAX) NOT NULL, 
    [SOUNDBOARD] NVARCHAR(MAX) NOT NULL, 
    [HEATSINK] NVARCHAR(MAX) NULL, 
    [GPUFAN] NVARCHAR(MAX) NULL
)
